# Generated by Django 4.0.2 on 2022-03-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='photo',
            field=models.ImageField(default=45, upload_to=''),
            preserve_default=False,
        ),
    ]
