# Generated by Django 4.0.2 on 2022-03-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0006_alter_register_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='photo',
        ),
    ]
